### PR TITLE
Added option to use cURL SSL CA bundle

### PR DESCRIPTION
**Pull request by dmitrijev**
Added option to use cURL SSL CA bundle if curl.cainfo is not set up in PHP.ini

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks good, but do we have a simple way of updating the bundled cacert.pem?

**Comment by dmitrijev** [comment]
One option is to download it automatically from https://curl.haxx.se/ca/cacert.pem but some PHP configurations might prevent that...

**Comment by ghost** [comment]
The reason I asked is because I don't see a reference to that URL in a README file, so it might be difficult for someone to update the bundled version. And do we really want to store the file in our repo?

We could either add a simple script that downloads the file to the right location, or update the build process to add it to the final zip file when making a release.

What do you think?

**Comment by dmitrijev** [comment]
For now, I think, manual update of the **cacert** on each new release is fine, later automatic update could be implemented.

**Pull request merged**
