### PR TITLE
Added a fix to missing bcmod function in PHP

### PR DESCRIPTION
**Pull request by dmitrijev**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
I don't really like the "Helper" name, it's very generic. Maybe something like "Compat" or "Fallback" would be better?

**Comment by dmitrijev** [comment]
I agree, will change.

**Review by ghost — APPROVED** [review]
Looking good!

**Comment by ghost** [comment]
Quick question, how does `my_bcmod` get used when `bc_mod` is not available?

**Review by ghost — APPROVED** [review]
Ah, like that :)

**Comment by ghost** [comment]
Can you also update your test? Looks like it didn't catch the issue...

**Comment by dmitrijev** [comment]
Unit test would have failed if PHP version installed on [Scrutinizer](https://travis-ci.org/gingerpayments/ginger-php/builds/161647920) would not have a **bcmod()** function available. Unit test just checks if the the bcmod() is available and returns correct value. If server does not have a BCMath extension loaded bcmod() would be defined in Fallback.php file and check it instead.

**Pull request merged**
