### PR TITLE
Ginger Payments API check for null values in JSON

### PR DESCRIPTION
**Pull request by dmitrijev**
So null values should be stripped out from the request body.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by ricovandevin** [comment]
This results in an error in my application:

> Error: Function name must be a string in GingerPayments\Payment\Common\ArrayFunctions::withoutNullValues() (line 19 of /path/to/ginger_php/src/Common/ArrayFunctions.php).

When I print `typeof($fn)` it returns 'string'. Something to do with PHP version?

**Comment by dmitrijev** [comment]
@ricovandevin Which PHP version are you using? 

If you would look into the code: 
https://github.com/gingerpayments/ginger-php/blob/master/src/Common/ArrayFunctions.php#L15

`$fn` is a predefined constant `__FUNCTION__` and should always be a string: 
http://php.net/manual/en/language.constants.predefined.php

which is used in recursion within the method itself as a static variable:
`
 $array[$key] = self::$fn($array[$key]);
`

it is used in this particular way so that method name could be changed without changing the code within the function itself. 

If you replace this line: https://github.com/gingerpayments/ginger-php/blob/master/src/Common/ArrayFunctions.php#L19

with this:
`
 $array[$key] = self::withoutNullValues($array[$key]);
`

does it solve error in your application?

**Comment by ricovandevin** [comment]
PHP version 7.0.0. Problem is solved when I remove the `static` in `static $fn = __FUNCTION__;`.

**Comment by dmitrijev** [comment]
@ricovandevin Could you please go to ginger-php root folder and run: 

`./vendor/bin/phpunit`

to check if phpunit can run the tests?

It seems to be working on PHP 7.0.13

**Comment by ricovandevin** [comment]
It is related to PHP version. When I switch the version back to 5.6 the problem is solved.

Also the tests are passing from the command line (where also PHP 5.6 is used).

`>/path/to/ginger_php   master  ./vendor/bin/phpunit`
`PHPUnit 4.8.26 by Sebastian Bergmann and contributors.
...............................................................  63 / 166 ( 37%)
............................................................... 126 / 166 ( 75%)
........................................
Time: 1.43 seconds, Memory: 15.75MB
OK (166 tests, 449 assertions)`

**Comment by dmitrijev** [comment]
Thank you very much for your input @ricovandevin

**Pull request merged**
